version: '3.6'
services:
  iris1:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    command: --check-caps false --ISCAgent false
    ports:
      - 41773:1972
      - 42773:52773
    volumes:
      - ./:/home/irisowner/dev
      - ./iris1:/iris1
    hostname: iris1

  iris2:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    command: --check-caps false --ISCAgent false
    ports:
      - 41663:1972
      - 42663:52773
    volumes:
      - ./:/home/irisowner/dev
      - ./iris2:/iris2
    hostname: iris2

  go-sscp:
    build:
      context: ./go-sscp
      dockerfile: Dockerfile
    restart: always
    environment:
      - SSCP_SOURCE=_SYSTEM:SYS@iris1:1972@USER:/iris1/TESTA.txt
      - SSCP_TARGET=_SYSTEM:SYS@iris2:1972@USER:/iris2/copyTESTA.txt
      - SSCP_INTERVAL=5s
      - SSCP_MODE=out-of-band
    depends_on:
      - iris1
      - iris2


